const series = [
    {
      title: "Breaking Bad",
      year: 2008,
      creator: "Vince Gilligan",
      seasons: 5,
      episodes: 62,
      genre: ["Crime", "Drama", "Thriller"],
      rate: 9.5,
      poster: "https://artworks.thetvdb.com/banners/posters/81189-10.jpg",
    },
    {
      title: "Game of Thrones",
      year: 2011,
      creator: "David Benioff, D.B. Weiss",
      seasons: 8,
      episodes: 73,
      genre: ["Action", "Adventure", "Drama", "Fantasy"],
      rate: 9.3,
      poster: "https://artworks.thetvdb.com/banners/posters/121361-4.jpg",
    },
    {
      title: "Stranger Things",
      year: 2016,
      creators: ["Matt Duffer", "Ross Duffer"],
      seasons: 4,
      episodes: 34,
      genre: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rate: 8.7,
      poster: "https://artworks.thetvdb.com/banners/posters/5d1df8d5be8c8.jpg",
    },
    {
      title: "The Crown",
      year: 2016,
      creator: "Peter Morgan",
      seasons: 4,
      episodes: 40,
      genre: ["Biography", "Drama", "History"],
      rate: 8.6,
      poster: "https://artworks.thetvdb.com/banners/v4/movie/1430/posters/649bdba443c6a.jpg",
    },
    {
      title: "The Office (US)",
      year: 2005,
      creators: ["Greg Daniels"],
      seasons: 9,
      episodes: 201,
      genre: ["Comedy"],
      rate: 8.9,
      poster: "https://artworks.thetvdb.com/banners/posters/73244-1.jpg",
    },
    {
      title: "Friends",
      year: 1994,
      creators: ["David Crane", "Marta Kauffman"],
      seasons: 10,
      episodes: 236,
      genre: ["Comedy", "Romance"],
      rate: 8.9,
      poster: "https://artworks.thetvdb.com/banners/posters/79168-27.jpg",
    }
  ];
  
 export default series;