const series = [
    {
      title: "Breaking Bad",
      year: 2008,
      creator: "Vince Gilligan",
      seasons: 5,
      episodes: 62,
      genre: ["Crime", "Drama", "Thriller"],
      rate: 9.5,
      poster: "https://www.cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FztkUQFLlC19CCMYHW9o1zWhJRNq.jpg&w=256&q=75",
    },
    {
      title: "Game of Thrones",
      year: 2011,
      creator: "David Benioff, D.B. Weiss",
      seasons: 8,
      episodes: 73,
      genre: ["Action", "Adventure", "Drama", "Fantasy"],
      rate: 9.3,
      poster: "https://www.cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2Fz9gCSwIObDOD2BEtmUwfasar3xs.jpg&w=256&q=75",
    },
    {
      title: "Stranger Things",
      year: 2016,
      creator: "Matt Duffer , Ross Duffer",
      seasons: 4,
      episodes: 34,
      genre: ["Drama", "Fantasy", "Horror", "Mystery", "Sci-Fi", "Thriller"],
      rate: 8.7,
      poster: "https://www.cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FwHhjZMlYGT9yUEyGpP9jmR6Jq3I.jpg&w=256&q=75",
    },
    {
      title: "The Crown",
      year: 2016,
      creator: "Peter Morgan",
      seasons: 4,
      episodes: 40,
      genre: ["Biography", "Drama", "History"],
      rate: 8.6,
      poster: "https://www.cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2F1ZMVKJoWK5KfxaQA8BwpfOEYKKy.jpg&w=256&q=75",
    },
    {
      title: "The Office (US)",
      year: 2005,
      creator: "Greg Daniels",
      seasons: 9,
      episodes: 201,
      genre: ["Comedy"],
      rate: 8.9,
      poster: "https://www.cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2F5uwetbr0X8BPRy3Wmh63S9EhsiY.jpg&w=256&q=75",
    },
    {
      title: "Friends",
      year: 1994,
      creator: "David Crane, Marta Kauffman",
      seasons: 10,
      episodes: 236,
      genre: ["Comedy", "Romance"],
      rate: 8.9,
      poster: "https://www.cuevana3.eu/_next/image?url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2FrkKCSlr8OH5tbKEdgwtzvEiemrl.jpg&w=256&q=75",
    }
  ];
  
module.exports=series;